export const API_ENDPOINTS = {
  REGISTER: "user-service/auth/register",
  REFRESH_TOKEN: "user-service/auth/refresh",
  LOGIN: "user-service/auth/login",
  UPDATE_PROFILE: "user-service/user/{userId}/profile",
  RESET_PASSWORD: "user-service/auth/reset-password",
  GET_USER_BY_ID: "user-service/user/{id}",
  SEARCH_USERS: 'user-service/user/search',
  GET_USER_PROFILE: 'user-service/user/{id}/profile',
  DELETE_PROFILE: 'user-service/user/{userId}',
  SEND_FRIEND_REQUEST: 'user-service/user/{userId}/friends/requests',
  RETRIEVE_USER_FRIEND_REQUESTS: 'user-service/user/{userId}/friend-requests',

  CREATE_EVENT: "event-service/event",
  GET_EVENT_BY_ID: "event-service/event/{id}",
  GET_ALL_EVENTS: "event-service/event",
  JOIN_EVENT_BY_ID: "event-service/event/{id}/join",
  DELETE_EVENT_BY_ID: "event-service/event/{id}",
  GET_ALL_EVENTS_CREATED_BY: 'event-service/event/created-by/{userId}',
  GET_EVENTS_BY_USER_ID: "event-service/event/participant/{userId}",
};
