#!/bin/bash

HOOKS_DIR="./ClientApp"

cd "$HOOKS_DIR" || { echo "Failed to navigate to $HOOKS_DIR"; exit 1; }

npm run ci-test

if [ $? -ne 0 ]; then
  echo "Tests failed or Coverage percentage not met. Push aborted."
  exit 1
else
  echo "***** Tests Passed ******"
  echo "***** Coverage is above 80% ******"
  echo "***** Done ******"
fi