name: Backend CI/CD

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - main
      - dev
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [user-service]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v4
        with:
          gradle-version: '8.10.2'

      - name: Build and Test Service with Gradle
        working-directory: ./microservices/${{ matrix.service }}
        run: ./gradlew clean build test

      - name: Run SonarCloud Analysis
        working-directory: ./microservices/${{ matrix.service }}
        run: ./gradlew sonarqube \
          -Dsonar.projectKey=SportsApp \
          -Dsonar.organization=your_organization_key \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      - name: Upload Test Results for Service
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: test-results-${{ matrix.service }}
          path: ./microservices/${{ matrix.service }}/build/reports/tests/test
