name: CI/CD Controller

on:
  pull_request:
    branches: [ "*" ]
  push:
    branches:
      - main
      - dev
      - 'releases/**'

jobs:
  determine-pipelines:
    runs-on: ubuntu-latest
    outputs:
      RUN_USERSERVICE_PIPELINE: ${{ steps.set-env.outputs.RUN_USERSERVICE_PIPELINE }}
      RUN_EVENTSERVICE_PIPELINE: ${{ steps.set-env.outputs.RUN_EVENTSERVICE_PIPELINE }}
      RUN_EMAILSERVICE_PIPELINE: ${{ steps.set-env.outputs.RUN_EMAILSERVICE_PIPELINE }}
      RUN_GATEWAYSERVICE_PIPELINE: ${{ steps.set-env.outputs.RUN_GATEWAYSERVICE_PIPELINE }}
      RUN_CLIENTAPP_PIPELINE: ${{ steps.set-env.outputs.RUN_CLIENTAPP_PIPELINE }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine Changed Files
        id: changed-files
        uses: tj-actions/changed-files@v36

      - name: Set Environment Variables for Services
        id: set-env
        run: |
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ "Microservices/user-service/" ]]; then
            echo "RUN_USERSERVICE_PIPELINE=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ "Microservices/event-service/" ]]; then
            echo "RUN_EVENTSERVICE_PIPELINE=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ "Microservices/email-service/" ]]; then
            echo "RUN_EMAILSERVICE_PIPELINE=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ "Microservices/gateway/" ]]; then
            echo "RUN_GATEWAYSERVICE_PIPELINE=true" >> $GITHUB_OUTPUT
          fi
          if [[ "${{ steps.changed-files.outputs.all_changed_files }}" =~ "ClientApp/" ]]; then
            echo "RUN_CLIENTAPP_PIPELINE=true" >> $GITHUB_OUTPUT
          fi

  trigger-workflows:
    needs: determine-pipelines
    runs-on: ubuntu-latest
    steps:
      - name: Trigger UserService CI/CD
        if: ${{ needs.determine-pipelines.outputs.RUN_USERSERVICE_PIPELINE == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: user-service-ci-cd.yml

      - name: Trigger EventService CI/CD
        if: ${{ needs.determine-pipelines.outputs.RUN_EVENTSERVICE_PIPELINE == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: event-service-ci-cd.yml

      - name: Trigger EmailService CI/CD
        if: ${{ needs.determine-pipelines.outputs.RUN_EMAILSERVICE_PIPELINE == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: email-service-ci-cd.yml

      - name: Trigger GatewayService CI/CD
        if: ${{ needs.determine-pipelines.outputs.RUN_GATEWAYSERVICE_PIPELINE == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: gateway-service-ci-cd.yml

      - name: Trigger ClientApp CI/CD
        if: ${{ needs.determine-pipelines.outputs.RUN_CLIENTAPP_PIPELINE == 'true' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: frontend-ci-cd.yml
