name: EmailService CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze UserService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build Project & Generate Test Reports
        working-directory: ./Microservices/email-service
        run: ./gradlew build jacocoTestReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_EMAILSERVICE }}
        with:
          args: >
            -D sonar.projectKey=sportaforked_EmailService
            -D sonar.organization=sportaforked
            -D sonar.host.url=https://sonarcloud.io
            -D sonar.java.binaries=Microservices/email-service/build/classes/java/main
            -D sonar.sources=Microservices/email-service/src/main/java
            -D sonar.tests=Microservices/email-service/src/test/java
            -D sonar.jacoco.reportPaths=Microservices/email-service/build/reports/jacoco/test/jacocoTestReport.xml