name: ClientApp CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: |
        npm install
      working-directory: ./ClientApp

    - name: Run tests and generate coverage
      run: |
        npm test --coverage --watchAll=false
      working-directory: ./ClientApp

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-

    - name: SonarCloud Scan
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENTAPP }}
      run: npm run sonar
      working-directory: ./ClientApp

    - name: Upload coverage to SonarCloud
      if: success()
      run: |
        curl -u ${{ secrets.SONAR_TOKEN_CLIENTAPP }} \
             -X POST -F "file=@coverage/lcov-report.json" \
             https://sonarcloud.io/api/coverage/upload
