name: ClientApp CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          npm install
        working-directory: ./ClientApp

      - name: Run tests and generate coverage
        run: |
          npm run generate-report
        working-directory: ./ClientApp

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENTAPP }}
        with:
          args: >
            -D sonar.projectKey=Sporta_SportsApp_ClientApp
            -D sonar.organization=soen490-sportsapp
            -D sonar.host.url=https://sonarcloud.io
            -D sonar.sources=ClientApp/
            -D sonar.tests=ClientApp/__tests__
            -D sonar.exclusions=ClientApp/__tests__/**
            -D sonar.javascript.lcov.reportPaths=ClientApp/coverage/lcov.info