name: ClientApp CI/CD

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Analyze
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Verify Java Version
      run: java -version

    - name: Install dependencies
      run: |
        npm install
      working-directory: ./ClientApp
      
    - name: Install sonar-scanner
      run: |
        npm install sonar-scanner
      working-directory: ./ClientApp

    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ./ClientApp/node_modules
        key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-modules-
          
    - name: Run tests and generate coverage
      run: |
        npm test --coverage --watchAll=false
      working-directory: ./ClientApp

    - name: Run SonarCloud Scan
      run: |
        npx sonar-scanner \
          -Dsonar.projectKey=sportaforked_ClientApp \
          -Dsonar.organization=sportaforked \
          -Dsonar.sources=./ \
          -Dsonar.host.url=https://sonarcloud.io \
          -Dsonar.login=${{ secrets.SONAR_TOKEN_CLIENTAPP }}
      working-directory: ./ClientApp
