name: ClientApp CI/CD

on:
  workflow_dispatch:

jobs:
  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4

  #     - name: Cache Node Modules
  #       uses: actions/cache@v4
  #       with:
  #         path: ~/.npm
  #         key: ${{ runner.os }}-node-${{ hashFiles('ClientApp/package-lock.json') }}
  #         restore-keys: |
  #           ${{ runner.os }}-node-
  #     - name: Install dependencies
  #       run: npm install
  #       working-directory: ./ClientApp

  #     - name: Lint with ESLint
  #       run: npm run lint
  #       working-directory: ./ClientApp

  test:
    # needs: lint
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install dependencies
        run: npm install
        working-directory: ./ClientApp
      
      - name: Cache Node Modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('ClientApp/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            
      - name: Run Jest Tests with Coverage
        run: npm test --coverage
        working-directory: ./ClientApp
        
  sonar:
    needs: test
    if: always()
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Install dependencies
        run: npm install
         
      - name: Test and coverage
        run: npm test --coverage

      - name: Build and Analyze with SonarQube
        working-directory: ./ClientApp
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLIENTAPP }}
