name: UserService CI/CD

on:
  workflow_dispatch:

jobs:
  build-and-analyze:
    name: Build and Analyze UserService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Build Project & Generate Test Reports
        working-directory: ./Microservices/user-service
        run: ./gradlew build jacocoTestReport

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USERSERVICE }}
        with:
          args: >
            -Dsonar.projectKey=sportaforked_UserService
            -Dsonar.organization=sportaforked
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=Microservices/user-service/build/classes/java/main
            -Dsonar.sources=Microservices/user-service/src/main/java
            -Dsonar.tests=Microservices/user-service/src/test/java
            -Dsonar.jacoco.reportPaths=Microservices/user-service/build/reports/jacoco/test/jacocoTestReport.xml