name: UserService CI

on:
  workflow_dispatch: 

jobs:
  build-and-analyze:
    name: Build and Analyze UserService
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'

      - name: Cache SonarQube Packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('Microservices/user-service/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Generate Test Coverage Report
        working-directory: Microservices/user-service
        run: ./gradlew test jacocoTestReport

      - name: Build and Analyze with SonarQube
        working-directory: Microservices/user-service
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_USERSERVICE }}
        run: ./gradlew build sonar --info
